### ISSUE TITLE
Deleted files and directories are not ignored

### ISSUE THREAD

**Issue by bignaux** [FranciscoDA/ps2mcfs#2]
430e454f4ba85468abe83f3923c8260455cb378e
introduce  Input/output error

```
find: ‘ps2/mc0/BESLES-50205’: Input/output error
ps2/mc0/BESLES-51511all
find: ‘ps2/mc0/BESLES-51511all’: Input/output error
ps2/mc0/BESLES-51511ad0
find: ‘ps2/mc0/BESLES-51511ad0’: Input/output error
```

7b4289a44947aadde24526edaaf57ca1fbdc7eb0
doesn't see  files in directories.

ff9d3716e6d955ce2aadd1f500b3c5abc43f1717:
some files in directories are not listed.

not sure about all, as if i browse in wLe, i don't see same directories, i try like BESLES-50205 doesn't appear there.
I use image create by MCA or lwnbd mcman plugin (similar sha256sum dump), so no ECC. Notice mcman plugin allows to mount real memorycard directly, not vmc.

**Comment by FranciscoDA** [comment]
Thanks for the report @bignaux 
Do you think you can produce a memory card file you could zip and upload here so I can better debug it?

Additionally, you can attempt debugging it on your own by using gdb and appending the `-f` flag at the end of the parameters.
E.g: `gdb --args ps2mcfs mcfile.vmc ./mount/point -f`

The `bt` command should print a backtrace on exception, but it will be hard to debug without the actual data that produces it.

**Comment by bignaux** [comment]
I'm working on the idea of an asset repo to share between different devel, CI and so, but i've to think about license ... right now i try to script ftp to use wLe ftp as reference for file listing. I donno much detail about mc, the plugin on lwnbd was original made by  one of your fellow citizens @parrado .

edit : 
```
# run with lftp -f lftp-script

set ftp:use-feat false
set ssl-allow false
user anonymous anonymous
open 192.168.1.45
find -l mc/1
```

**Comment by FranciscoDA** [comment]
@bignaux Are you using lwNBD? If you mounted the MC in say /dev/nbd2 you could copy it to a file like so: `dd if=/dev/nbd2 of=./ps2.mc bs=512` but please be careful when setting the output path.

Reproducing your setup is a bit complicated for me as I don't have access to a physical PS2 atm

**Comment by FranciscoDA** [comment]
@bignaux could you please test the branch from #3 and confirm if the problem persists? apologies for the mistake

**Comment by bignaux** [comment]
It looks like ps2mcs has issue when it try to list deleted file . I use isobuster since @Nadwiślański told me it has deleted files support and that confirms : https://pasteboard.co/gAEurmuc2hz5.png . The dump is here https://file.io/aVbLtJlmmV2Z (created with MCA).

**Comment by FranciscoDA** [comment]
Thanks @bignaux i've tested your file and confirmed that this error is caused by ps2mcfs not ignoring files and directories that have been marked as deleted

**Comment by bignaux** [comment]
once fixed i'd verify with lftp dump ( mirror mc/1 ), see if we get convergence here. any idea if you'll get real write support soon ?

**Comment by FranciscoDA** [comment]
@bignaux please try the latest source from master.

Sadly we're still far off from real write support. I'm still not completely sure all the write operations are implemented correctly, we will need unit tests for that. Otherwise we risk corrupting valid memory card files

**Comment by bignaux** [comment]
i did an archive for file dump from lftp https://file.io/uRb3oCRDP6k1 , we have one file that is bad read in ps2mcfs for this dump: 
```
$ LANG=C diff -qr mc1/ ../../assets/ps2/mc0/
Files mc1/BESLES-52783/BESLES-52783_0.chk and ../../assets/ps2/mc0/BESLES-52783/BESLES-52783_0.chk differ
```

**Comment by FranciscoDA** [comment]
@bignaux Please try the latest source from master again, I think I've fixed the problem.
Feel free to close this issue and open a new one if you find additional problems. Thanks for your assistance!

**Comment by bignaux** [comment]
That's ok for me. I think we have a begin of tool to check regression now.
